import type { Metadata } from "next";
import localFont from 'next/font/local';

const aeronaut = localFont({
  variable: "--font-aeronaut",
  src: "./font/Aeronaut.woff2"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="no" suppressHydrationWarning className={`${aeronaut.variable}`}>
      {children}
    </html>
  );
}
