import { QueryProvider } from "@/common/providers/query-provider";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const aeronaut = localFont({
  variable: "--font-aeronaut",
  src: "./font/Aeronaut.woff2"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="no" suppressHydrationWarning className={`${aeronaut.variable}`}>
      <QueryProvider>
        {children}
      </QueryProvider>
    </html>
  );

}
